/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AnnotationAssistResult,  AnnotationSuggestion,  BrooderAnnotation,  ChickAnswer,  ChickDetection,  ChickIdentity,  ChickObservation,  DraftAnnotation } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AnnotationAssistResult {
      guidance?: string | null
      suggestions: AnnotationSuggestion[]
      quality_checks: string[]
    }
    export interface AnnotationSuggestion {
      label?: "chick" | "heater" | "water" | "food" | "waste" | "bedding" | null
      kind?: "box" | "corners" | "point" | null
      reason?: string | null
    }
    export interface BrooderAnnotation {
      label?: string | null
      kind?: "box" | "corners" | "point" | null
      bounding_box?: number[] | null
      corners?: number[][] | null
      point?: number[] | null
      frame_id?: string | null
      created_by?: string | null
    }
    export interface ChickAnswer {
      answer?: string | null
      confidence?: "low" | "medium" | "high" | null
      safety_level?: "normal" | "check_now" | "adult_attention" | null
      suggested_checks: string[]
      evidence: string[]
      follow_up_questions: string[]
    }
    export interface ChickDetection {
      track_id?: string | null
      class_name?: string | null
      bbox: number[]
      confidence?: number | null
      zone?: string | null
      activity?: string | null
    }
    export interface ChickIdentity {
      track_id?: string | null
      name?: string | null
    }
    export interface ChickObservation {
      timestamp?: string | null
      comfort_score?: number | null
      summary?: string | null
      alerts: string[]
      heater_zone_pct_10m?: number | null
      food_water_zone_pct_10m?: number | null
      movement_score?: number | null
    }
    export interface DraftAnnotation {
      label?: string | null
      kind?: "box" | "corners" | "point" | null
      bounding_box?: number[] | null
      corners?: number[][] | null
      point?: number[] | null
      image_size?: number[] | null
    }
}