/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, HTTPRequest } from "@boundaryml/baml"
import { toBamlError, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AnnotationAssistResult, AnnotationSuggestion, BrooderAnnotation, ChickAnswer, ChickDetection, ChickIdentity, ChickObservation, DraftAnnotation} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  env?: Record<string, string | undefined>
  events?: EventsT
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnswerChickQuestion(
      question: string,latest_observation: types.ChickObservation,recent_observations: types.ChickObservation[],manual_notes: string[],knowledge_snippets: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AnswerChickQuestion",
        {
          "question": question,"latest_observation": latest_observation,"recent_observations": recent_observations,"manual_notes": manual_notes,"knowledge_snippets": knowledge_snippets
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssistBrooderAnnotation(
      latest_observation: types.ChickObservation,detections: types.ChickDetection[],existing_annotations: types.BrooderAnnotation[],chick_identities: types.ChickIdentity[],draft: types.DraftAnnotation,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AssistBrooderAnnotation",
        {
          "latest_observation": latest_observation,"detections": detections,"existing_annotations": existing_annotations,"chick_identities": chick_identities,"draft": draft
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnswerChickQuestion(
      question: string,latest_observation: types.ChickObservation,recent_observations: types.ChickObservation[],manual_notes: string[],knowledge_snippets: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AnswerChickQuestion",
        {
          "question": question,"latest_observation": latest_observation,"recent_observations": recent_observations,"manual_notes": manual_notes,"knowledge_snippets": knowledge_snippets
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssistBrooderAnnotation(
      latest_observation: types.ChickObservation,detections: types.ChickDetection[],existing_annotations: types.BrooderAnnotation[],chick_identities: types.ChickIdentity[],draft: types.DraftAnnotation,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AssistBrooderAnnotation",
        {
          "latest_observation": latest_observation,"detections": detections,"existing_annotations": existing_annotations,"chick_identities": chick_identities,"draft": draft
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}
