/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AnnotationAssistResult {
  guidance: string
  suggestions: AnnotationSuggestion[]
  quality_checks: string[]
  
}

export interface AnnotationSuggestion {
  label: "chick" | "heater" | "water" | "food" | "waste" | "bedding"
  kind: "box" | "point"
  reason: string
  
}

export interface BrooderAnnotation {
  label: string
  kind: "box" | "point"
  bounding_box?: number[] | null
  point?: number[] | null
  frame_id?: string | null
  created_by: string
  
}

export interface ChickAnswer {
  answer: string
  confidence: "low" | "medium" | "high"
  safety_level: "normal" | "check_now" | "adult_attention"
  suggested_checks: string[]
  evidence: string[]
  follow_up_questions: string[]
  
}

export interface ChickDetection {
  track_id: string
  class_name: string
  bbox: number[]
  confidence: number
  zone: string
  activity: string
  
}

export interface ChickIdentity {
  track_id: string
  name: string
  
}

export interface ChickObservation {
  timestamp: string
  comfort_score: number
  summary: string
  alerts: string[]
  heater_zone_pct_10m: number
  food_water_zone_pct_10m: number
  movement_score: number
  
}

export interface DraftAnnotation {
  label?: string | null
  kind: "box" | "point"
  bounding_box?: number[] | null
  point?: number[] | null
  image_size?: number[] | null
  
}
